### ISSUE TITLE
Send `site_id` meta slot with an intent

### ISSUE THREAD

**Issue by bk90** [rhasspy/rhasspy-homeassistant-hermes#2]
I'm moving from Snips to Rhasspy and am missing the `site_id` meta slot in the intents. For me knowledge of where (=in which room) a voice command/intent originated is very useful. For example, so that I can say *Turn the lights on* to turn on the lights in the room in which I currently am.

I guess it needs to be added below https://github.com/rhasspy/rhasspy-homeassistant-hermes/blob/d78c9286171b593ced42608aa70a3c703d0516ec/rhasspyhomeassistant_hermes/__init__.py#L150, I just don't know where to get it from.

Thank you for creating this great application!

**Comment by synesthesiam** [comment]
Pull request has finally been merged. Thanks for your patience!
